# Generated by Django 3.2.8 on 2022-03-16 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220314_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='chatterpost',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
