# Generated by Django 4.0.3 on 2022-03-21 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20220316_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
    ]
