# Generated by Django 4.0.3 on 2022-03-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_follow_post_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.BooleanField(default=False),
        ),
    ]
