# Generated by Django 4.0.3 on 2022-03-22 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_like_remove_post_follow_post_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='follow',
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
