# Generated by Django 4.0.3 on 2022-03-24 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_remove_post_like_post_likedby_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likedby',
        ),
        migrations.AlterField(
            model_name='post',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
