# Generated by Django 4.0.3 on 2022-03-30 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_post_likedby_alter_post_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likedby',
            field=models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
