# Generated by Django 4.0.3 on 2022-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_post_likedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
